spring.application.name=demo

# Nombre del microservicio
# Puerto del servicio
server.port=8082

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/arco_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logs SQL para desarrollo
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Evitar conflicto con Docker Compose si no lo usas
spring.docker.compose.enabled=false
